services:
  soularr:
    restart: unless-stopped
    container_name: soularr
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      #Script interval in seconds
      - SCRIPT_INTERVAL=30
    user: "root:root" 
    volumes:
      - /mnt/Plex11/slskd/complete:/mnt/Plex11/slskd/complete
      #"You can set /downloads to whatever you want but will then need to change the Slskd download dir in your config file"
      - /mnt/Plex11/slskd/complete:/downloads
      #Select where you are storing your config file.
      #Leave "/data" since thats where the script expects the config file to be
      - /home/eric/Soularr:/data
    image: mrusse08/soularr:latest
    command: sh -c "python soularr.py 2>&1 | tee -a /data/soularr.log"
  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: soularr-dashboard
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /home/eric/Soularr/dashboard:/app
      - /home/eric/Soularr:/data
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app

