services:
  dashboard:
    build: .
    container_name: soularr-dashboard
    network_mode: "host" 
    volumes:
      - /opt/Soularr_docker/logs:/logs
      - /opt/Soularr_docker/config:/data
    environment:
      - TZ=America/Los_Angeles
      - LOG_PATH=/logs/soularr.log
      - FAILURE_PATH=/data/failure_list.txt
    restart: unless-stopped
=======
  soularr:
    restart: unless-stopped
    container_name: soularr
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - SCRIPT_INTERVAL=30
    user: "root:root"
    volumes:
      - /mnt/Plex11/slskd/complete:/mnt/Plex11/slskd/complete
      - /mnt/Plex11/slskd/complete:/downloads
      - /home/eric/Soularr:/data
      - /home/eric/Soularr/data/logs:/data/logs
    image: mrusse08/soularr:latest
    command: sh -c "mkdir -p /data/logs && python soularr.py 2>&1 | tee -a /data/logs/soularr.log"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: soularr-dashboard
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /home/eric/Soularr/dashboard:/app
      - /home/eric/Soularr:/data
      - /home/eric/Soularr/data/logs:/data/logs
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app

